brand: "Fendex"

email: "rendexfendex@gmail.com"
telegram_url: "https://t.me/Arshaklol32323333"
telegram_name: "@Arshaklol32323333"

storage_base_url: "https://fendex.github.io/Model_viewer/assets/models"

price_10_ru: "от 5 000 ₽"
price_50_ru: "от 15 000 ₽"

price_10_en: "from 5,000 RUB"
price_50_en: "from 15,000 RUB"
